Marging Trade (PostBorrowOrder, GetBorrowOrder & PaySingleBorrowOrder)
JKorf/Kucoin.Net pull request #60
Opened 2021-09-23 20:36 UTC by hammadsajid786

Marging Trade #47  fix added

Methods Added
https://docs.kucoin.com/#post-borrow-order (PlaceBorrowOrderAsync)
https://docs.kucoin.com/#get-borrow-order (GetBorrowOrderByClientOrderIdAsync)
https://docs.kucoin.com/#repay-a-single-order (RepaySingleBorrowOrderAsync)

2021-09-23 20:40 UTC, hammadsajid786 reviewed
Changes Tested.
Working fine.

2021-09-24 06:33 UTC, JKorf requested changes
Thanks for you PR, please have a look at the comments

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Interfaces/IKucoinClientSpot.cs
> +           string currency,
To keep this in line with the rest of the implementations, this should be called `asset`

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Interfaces/IKucoinClientSpot.cs
> +        /// <param name="term">erm (Unit: Day). All terms are acceptable if this field is left empty. Please note to separate the terms via comma. For example, 7,14,28</param>
Typo `erm` -> `term`

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/SubClients/KucoinClientSpot.cs
> +        public async Task<WebCallResult<KucoinBorrowOrder>> GetBorrowOrderByClientOrderIdAsync(string clientOrderId, CancellationToken ct = default)
I don't think this is actually by `clientOrderId`. By `clientOrderId` would be when you can retrieve the order by an id you passed in when placing the order. This is a generated id, so this should just be called `GetBorrowOrderAsync` and the parameter should be `orderId`

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Interfaces/IKucoinClientSpot.cs
> +        /// <param name="currency">Currency to Pay e.g USDT etc</param>
`asset`

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Interfaces/IKucoinClientSpot.cs
> +        /// <returns>The id of the new order</returns>
Doesn't return anything

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Objects/Spot/KucoinBorrowOrder.cs
> +        public string Currency { get; set; } = string.Empty;
`Asset`

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Objects/Spot/KucoinBorrowOrder.cs
> +        public string Status { get; set; } = string.Empty;
Should be an enum with values `Done` and `Processing`

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Objects/Spot/KucoinBorrowOrder.cs
> +        public string Currency { get; set; } = string.Empty;
`Asset`

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Objects/Spot/KucoinBorrowOrder.cs
> +        public string DailyIntRate { get; set; } = string.Empty;
`decimal`

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Objects/Spot/KucoinBorrowOrder.cs
> +        /// Total size of the borrow order
Incorrect summary

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Objects/Spot/KucoinBorrowOrder.cs
> +        [JsonProperty("timestamp"), JsonConverter(typeof(TimestampNanoSecondsConverter))]
According to the docs this is in milliseconds, not nanoseconds

2021-09-24 06:33 UTC, JKorf commented on Kucoin.Net/Objects/Spot/KucoinNewBorrowOrder.cs
> +        public string Currency { get; set; } = string.Empty;
`Asset`

2021-11-03 10:09 UTC, JKorf approved these changes

2021-11-03 10:09 UTC, merged